#!/usr/bin/env node
// seed.js — Populate the framing app with plausible Phil-style orders.
//
// Usage:
//   ./start.sh --db &      # start grove-server with persistence
//   node seed.js           # seed
//
// Re-running creates duplicates. Delete framing.sqlite to start clean.
//
// Note: this script POSTs directly to grove-server (not through serve.py),
// so ticket_no must be supplied explicitly. Real intakes via the iPad UI
// get ticket_no auto-assigned by serve.py.

import { callAction } from "./agents/lib/grove.js";

const API = process.env.GROVE_SERVER || "http://127.0.0.1:3000";

function isoDate(daysFromToday) {
  const d = new Date();
  d.setDate(d.getDate() + daysFromToday);
  return d.toISOString().slice(0, 10);
}

const ORDERS = [
  {
    ticket_no: "0045670",
    customer_name: "Margaret Liu",
    customer_phone: "914-555-0101",
    customer_address: "12 Elm St, White Plains, NY",
    customer_zip: "10605",
    customer_email: "mliu@example.com",
    date_received: isoDate(-2),
    date_promised: isoDate(10),
    description_of_item: "Pencil sketch from grandfather, fragile edges",
    declared_value: "350",
    frame_size: "18 x 24",
    frame_molding_no: "LJ-372181",
    frame_feet: "7",
    frame_price_per_foot: "2.85",
    frame_amount: "19.95",
    mat1_type: "double mat",
    mat1_color: "Ivory",
    mat1_margin_top_in: "2",
    mat1_margin_sides_in: "2",
    mat1_margin_bottom_in: "2.5",
    mat1_amount: "28.00",
    mat2_type: "bottom mat",
    mat2_color: "Charcoal",
    mat2_amount: "12.00",
    glass_kind: "non_glare",
    glass_amount: "45.00",
    mount_kind: "museum",
    mount_backer_type: "Acid-free foamcore",
    mount_amount: "18.00",
    hanger_kind: "wire",
    hanger_amount: "4.00",
    special_instructions: "Pencil sketch from grandfather, fragile edges. No spray. Hinge mount only.",
    subtotal: "126.95",
    tax_amount: "10.63",
    total: "137.58",
    deposit_amount: "120.00",
    balance_due: "17.58",
    advance_to: "cutting_materials",
  },
  {
    ticket_no: "0045671",
    customer_name: "Dave Okonkwo",
    customer_phone: "914-555-0144",
    date_received: isoDate(-5),
    date_promised: isoDate(2),
    description_of_item: "Photo print, 1970s, color tones warm",
    frame_size: "20 x 16",
    frame_molding_no: "ST-1011",
    frame_feet: "6",
    frame_price_per_foot: "2.10",
    frame_amount: "12.60",
    mat1_type: "single mat",
    mat1_color: "Cream",
    mat1_margin_top_in: "1.5",
    mat1_margin_sides_in: "1.5",
    mat1_margin_bottom_in: "1.5",
    mat1_amount: "18.00",
    glass_kind: "non_glare",
    glass_amount: "32.00",
    mount_kind: "dry",
    mount_amount: "10.00",
    hanger_kind: "sawtooth",
    hanger_amount: "3.00",
    special_instructions: "Customer wants warm tone preserved.",
    subtotal: "75.60",
    tax_amount: "6.33",
    total: "81.93",
    deposit_amount: "40.00",
    balance_due: "41.93",
    advance_to: "assembly",
  },
  {
    ticket_no: "0045672",
    customer_name: "Priya Shankar",
    customer_phone: "914-555-0188",
    customer_email: "priya.s@example.com",
    date_received: isoDate(-7),
    date_promised: isoDate(-1),
    description_of_item: "College diploma, float-mounted",
    frame_size: "11 x 14",
    frame_molding_no: "MB-100",
    frame_feet: "4.16",
    frame_price_per_foot: "1.80",
    frame_amount: "7.49",
    glass_kind: "regular",
    glass_amount: "18.00",
    mount_kind: "dry",
    mount_amount: "8.00",
    hanger_kind: "wire",
    hanger_amount: "3.00",
    service_fitting: true,
    services_amount: "6.00",
    special_instructions: "Float so corners are visible.",
    subtotal: "42.49",
    tax_amount: "3.56",
    total: "46.05",
    deposit_amount: "25.00",
    balance_due: "21.05",
    advance_to: "ready_for_pickup",
  },
  {
    ticket_no: "0045664",
    customer_name: "Theresa Donnelly",
    customer_phone: "914-555-0220",
    customer_address: "44 Soundview Ave, White Plains, NY",
    customer_zip: "10606",
    customer_email: "tdonnelly@example.com",
    date_received: isoDate(0),
    date_promised: isoDate(14),
    description_of_item: "Son's wedding photo, b&w, 16x20 print",
    declared_value: "250",
    frame_size: "20 x 24",
    frame_molding_no: "LJ-118400",
    frame_feet: "7.5",
    frame_price_per_foot: "3.40",
    frame_amount: "25.50",
    mat1_type: "single mat",
    mat1_color: "Linen White",
    mat1_margin_top_in: "2",
    mat1_margin_sides_in: "2",
    mat1_margin_bottom_in: "2.5",
    mat1_amount: "32.00",
    glass_kind: "non_glare",
    glass_amount: "48.00",
    mount_kind: "dry",
    mount_amount: "14.00",
    hanger_kind: "wire",
    hanger_amount: "4.00",
    special_instructions: "Wife's gift, do not bend or crease. Customer prefers slight bottom weight on mat.",
    subtotal: "123.50",
    tax_amount: "10.34",
    total: "133.84",
    deposit_amount: "70.00",
    balance_due: "63.84",
    advance_to: "intake",
  },
  {
    ticket_no: "0045665",
    customer_name: "Ramon Vasquez",
    customer_phone: "914-555-0317",
    customer_address: "9 Greenridge Ave, White Plains, NY",
    customer_zip: "10605",
    date_received: isoDate(-1),
    date_promised: isoDate(12),
    description_of_item: "Small oil on canvas, harbor scene, signed",
    declared_value: "800",
    frame_size: "14 x 11",
    frame_molding_no: "RB-2240",
    frame_feet: "4.5",
    frame_price_per_foot: "4.20",
    frame_amount: "18.90",
    liner_size: "14 x 11",
    liner_no: "LN-88",
    liner_feet: "4.5",
    liner_price_per_foot: "2.00",
    liner_amount: "9.00",
    glass_kind: "plexi",
    glass_amount: "0.00",
    mount_kind: "dry",
    mount_amount: "0.00",
    hanger_kind: "wire",
    hanger_amount: "4.00",
    special_instructions: "Oil — NO glass. Linen liner only. Handle by edges only.",
    subtotal: "31.90",
    tax_amount: "2.67",
    total: "34.57",
    deposit_amount: "20.00",
    balance_due: "14.57",
    advance_to: "cutting_materials",
  },
  {
    ticket_no: "0045666",
    customer_name: "Aisha Patel",
    customer_phone: "914-555-0402",
    customer_email: "apatel@example.com",
    date_received: isoDate(-3),
    date_promised: isoDate(5),
    description_of_item: "Botanical print, watercolor, 11x14",
    declared_value: "150",
    frame_size: "16 x 20",
    frame_molding_no: "LJ-510205",
    frame_feet: "6",
    frame_price_per_foot: "2.60",
    frame_amount: "15.60",
    mat1_type: "double mat",
    mat1_color: "Sage",
    mat1_margin_top_in: "2",
    mat1_margin_sides_in: "2",
    mat1_margin_bottom_in: "2",
    mat1_amount: "26.00",
    mat2_type: "bottom mat",
    mat2_color: "Cream",
    mat2_amount: "10.00",
    glass_kind: "regular",
    glass_amount: "22.00",
    mount_kind: "dry",
    mount_amount: "10.00",
    hanger_kind: "sawtooth",
    hanger_amount: "3.00",
    special_instructions: "Reveal of cream mat ~1/4 inch.",
    subtotal: "86.60",
    tax_amount: "7.25",
    total: "93.85",
    deposit_amount: "50.00",
    balance_due: "43.85",
    advance_to: "assembly",
  },
  {
    ticket_no: "0045667",
    customer_name: "Jim Hochberg",
    customer_phone: "914-555-0511",
    customer_address: "212 Bryant Ave, White Plains, NY",
    customer_zip: "10605",
    date_received: isoDate(-9),
    date_promised: isoDate(-2),
    description_of_item: "1977 Yankees championship poster, slight foxing top edge",
    declared_value: "400",
    frame_size: "24 x 36",
    frame_molding_no: "ST-3300",
    frame_feet: "10",
    frame_price_per_foot: "2.95",
    frame_amount: "29.50",
    mat1_type: "single mat",
    mat1_color: "Navy",
    mat1_margin_top_in: "2.5",
    mat1_margin_sides_in: "2.5",
    mat1_margin_bottom_in: "3",
    mat1_amount: "44.00",
    glass_kind: "non_glare",
    glass_amount: "78.00",
    mount_kind: "museum",
    mount_backer_type: "Acid-free foamcore",
    mount_amount: "26.00",
    hanger_kind: "wire",
    hanger_amount: "5.00",
    service_fitting: true,
    services_amount: "8.00",
    special_instructions: "Hinge mount, do not trim margins, foxing stays as-is.",
    subtotal: "190.50",
    tax_amount: "15.96",
    total: "206.46",
    deposit_amount: "206.46",
    balance_due: "0.00",
    advance_to: "ready_for_pickup",
  },
  {
    ticket_no: "0045668",
    customer_name: "Sofia Greco",
    customer_phone: "914-555-0633",
    date_received: isoDate(0),
    date_promised: isoDate(21),
    description_of_item: "Daughter's kindergarten finger painting on cardstock",
    frame_size: "12 x 16",
    frame_molding_no: "MB-208",
    frame_feet: "5",
    frame_price_per_foot: "1.60",
    frame_amount: "8.00",
    mat1_type: "single mat",
    mat1_color: "Bright White",
    mat1_margin_top_in: "1.5",
    mat1_margin_sides_in: "1.5",
    mat1_margin_bottom_in: "1.5",
    mat1_amount: "14.00",
    glass_kind: "regular",
    glass_amount: "18.00",
    mount_kind: "dry",
    mount_amount: "8.00",
    hanger_kind: "sawtooth",
    hanger_amount: "3.00",
    special_instructions: "Customer wants visible finger texture — light pressure on the press.",
    subtotal: "51.00",
    tax_amount: "4.27",
    total: "55.27",
    deposit_amount: "0.00",
    balance_due: "55.27",
    advance_to: "intake",
  },
  {
    ticket_no: "0045669",
    customer_name: "Walter Bremmer",
    customer_phone: "914-555-0744",
    customer_address: "78 Old Mamaroneck Rd, White Plains, NY",
    customer_zip: "10605",
    customer_email: "wbremmer@example.com",
    date_received: isoDate(-4),
    date_promised: isoDate(6),
    description_of_item: "Vintage 1920s NYC subway map, lithograph, brittle",
    declared_value: "600",
    frame_size: "22 x 28",
    frame_molding_no: "LJ-441230",
    frame_feet: "9",
    frame_price_per_foot: "3.75",
    frame_amount: "33.75",
    mat1_type: "single mat",
    mat1_color: "Warm Gray",
    mat1_margin_top_in: "2.5",
    mat1_margin_sides_in: "2.5",
    mat1_margin_bottom_in: "3",
    mat1_amount: "38.00",
    glass_kind: "non_glare",
    glass_amount: "62.00",
    mount_kind: "museum",
    mount_backer_type: "Rag board, acid-free",
    mount_amount: "22.00",
    hanger_kind: "wire",
    hanger_amount: "5.00",
    service_repair: true,
    services_amount: "15.00",
    special_instructions: "Tape repair on lower-right corner before mounting. UV-filter glass requested by customer.",
    subtotal: "175.75",
    tax_amount: "14.72",
    total: "190.47",
    deposit_amount: "100.00",
    balance_due: "90.47",
    advance_to: "assembly",
  },
];

const TRANSITIONS = {
  intake: [],
  cutting_materials: ["start_cutting"],
  assembly: ["start_cutting", "start_assembly"],
  ready_for_pickup: ["start_cutting", "start_assembly", "mark_ready"],
};

async function seed() {
  console.log(`Seeding ${ORDERS.length} orders against ${API}...\n`);

  let ok = 0, fail = 0;

  for (const o of ORDERS) {
    const { advance_to, ...createBody } = o;
    for (const k of Object.keys(createBody)) {
      if (createBody[k] === "") delete createBody[k];
    }

    try {
      const res = await callAction("create", createBody, API);
      const id = res.record.id;
      const transitions = TRANSITIONS[advance_to] || [];
      for (const t of transitions) {
        await callAction(t, { id }, API);
      }
      console.log(`  ok  #${o.ticket_no}  ${o.customer_name.padEnd(20)} -> ${advance_to}`);
      ok++;
    } catch (e) {
      console.error(`  err #${o.ticket_no}  ${o.customer_name}: ${e.message}`);
      fail++;
    }
  }

  console.log(`\nDone. ${ok} ok, ${fail} failed.`);
}

seed().catch(e => { console.error(e); process.exit(1); });
